### ISSUE TITLE
为 reitit 增加对 java.time.Instant 对象转换为 json 字符串时的强制 3 位毫秒数字的格式

### ISSUE THREAD

**Issue by xzj** [coders-at-work/ladybird#25]
### 问题描述
- reitit 在把 java.time.Instant 对象转换为 response body 里面的 json 时，使用的时间字符串格式，会忽略小数点后最低位的 0. 比如，时间值为 "1980-04-09T10:15:30.00000Z" 的 Instant 对象，转换为 json 后的字符串是 "1980-04-09T10:15:30Z"。
- 这样会造成 api 返回的时间字段的格式不够统一
- 为此，希望可以定制 Instant 对象转换为 json 的时间字符串格式，强制保留 3 位毫秒数字。比如，时间值为 "1980-04-09T10:15:30.00000Z" 的 Instant 对象，转换为 json 后的字符串是 "1980-04-09T10:15:30.000Z"。

### 解决方案
- 要定制 Instant 对象转换为 json 的格式，需要用 reitit route data 里面的 :muuntaja key. 参考 [Content Negotiation](https://cljdoc.org/d/metosin/reitit/0.5.12/doc/ring/content-negotiation).
- 在定制 encoder 的过程中，发现 reitit 所依赖的 json 库 jsonista，使用了特定的 module(com.fasterxml.jackson.datatype.jsr310.JavaTimeModule) 做 json 的时间转换。这个 module 没有办法替换，也不能配置。所以，只能使用自定义的 module 去覆盖 JavaTimeModule 对 Instant 对象的处理逻辑。参考 **jsonista.core/object-mapper** 的代码。
- 当前 ladybird.util.reitit/default-muuntaja 是自定义的 reitit json decoder/encoder 配置。所以，要修改其实现，加上自定义 module 对 Instant 对象的 json 转换做处理。

**Comment by gzeureka** [comment]
Fixed by PR https://github.com/coders-at-work/ladybird/pull/28
